### ISSUE TITLE
Why not to have "ejabberd-translations" like name?

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd-po#2]
Really good to have a separated repository for translation base files.

Why not to have "ejabberd-translations" like name instead of "ejabberd-po"?

**Comment by badlop** [comment]
Why?

**Comment by Neustradamus** [comment]
More clear.

**Comment by badlop** [comment]
That is not more clear, it is more confusing.

Translations are split in *.msg files for ejabberd, and *.po files for translators. In that sense, the *.msg files are in ejabberd/priv/msgs/, and the *.po files are in ejabberd-po/. Those two paths, in conjunction, contain all the translations.

**Comment by Neustradamus** [comment]
@badlop: But `ejabberd/priv/msgs` can be `ejabberd/translations` or `ejabberd/priv/translations`, no?
